<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = array(
            array('id' => '1','shortname' => 'AF','name' => 'Afghanistan','phonecode' => '93'),
            array('id' => '2','shortname' => 'AL','name' => 'Albania','phonecode' => '355'),
            array('id' => '3','shortname' => 'DZ','name' => 'Algeria','phonecode' => '213'),
            array('id' => '4','shortname' => 'AS','name' => 'American Samoa','phonecode' => '1684'),
            array('id' => '5','shortname' => 'AD','name' => 'Andorra','phonecode' => '376'),
            array('id' => '6','shortname' => 'AO','name' => 'Angola','phonecode' => '244'),
            array('id' => '7','shortname' => 'AI','name' => 'Anguilla','phonecode' => '1264'),
            array('id' => '8','shortname' => 'AQ','name' => 'Antarctica','phonecode' => '0'),
            array('id' => '9','shortname' => 'AG','name' => 'Antigua And Barbuda','phonecode' => '1268'),
            array('id' => '10','shortname' => 'AR','name' => 'Argentina','phonecode' => '54'),
            array('id' => '11','shortname' => 'AM','name' => 'Armenia','phonecode' => '374'),
            array('id' => '12','shortname' => 'AW','name' => 'Aruba','phonecode' => '297'),
            array('id' => '13','shortname' => 'AU','name' => 'Australia','phonecode' => '61'),
            array('id' => '14','shortname' => 'AT','name' => 'Austria','phonecode' => '43'),
            array('id' => '15','shortname' => 'AZ','name' => 'Azerbaijan','phonecode' => '994'),
            array('id' => '16','shortname' => 'BS','name' => 'Bahamas The','phonecode' => '1242'),
            array('id' => '17','shortname' => 'BH','name' => 'Bahrain','phonecode' => '973'),
            array('id' => '18','shortname' => 'BD','name' => 'Bangladesh','phonecode' => '880'),
            array('id' => '19','shortname' => 'BB','name' => 'Barbados','phonecode' => '1246'),
            array('id' => '20','shortname' => 'BY','name' => 'Belarus','phonecode' => '375'),
            array('id' => '21','shortname' => 'BE','name' => 'Belgium','phonecode' => '32'),
            array('id' => '22','shortname' => 'BZ','name' => 'Belize','phonecode' => '501'),
            array('id' => '23','shortname' => 'BJ','name' => 'Benin','phonecode' => '229'),
            array('id' => '24','shortname' => 'BM','name' => 'Bermuda','phonecode' => '1441'),
            array('id' => '25','shortname' => 'BT','name' => 'Bhutan','phonecode' => '975'),
            array('id' => '26','shortname' => 'BO','name' => 'Bolivia','phonecode' => '591'),
            array('id' => '27','shortname' => 'BA','name' => 'Bosnia and Herzegovina','phonecode' => '387'),
            array('id' => '28','shortname' => 'BW','name' => 'Botswana','phonecode' => '267'),
            array('id' => '29','shortname' => 'BV','name' => 'Bouvet Island','phonecode' => '0'),
            array('id' => '30','shortname' => 'BR','name' => 'Brazil','phonecode' => '55'),
            array('id' => '31','shortname' => 'IO','name' => 'British Indian Ocean Territory','phonecode' => '246'),
            array('id' => '32','shortname' => 'BN','name' => 'Brunei','phonecode' => '673'),
            array('id' => '33','shortname' => 'BG','name' => 'Bulgaria','phonecode' => '359'),
            array('id' => '34','shortname' => 'BF','name' => 'Burkina Faso','phonecode' => '226'),
            array('id' => '35','shortname' => 'BI','name' => 'Burundi','phonecode' => '257'),
            array('id' => '36','shortname' => 'KH','name' => 'Cambodia','phonecode' => '855'),
            array('id' => '37','shortname' => 'CM','name' => 'Cameroon','phonecode' => '237'),
            array('id' => '38','shortname' => 'CA','name' => 'Canada','phonecode' => '1'),
            array('id' => '39','shortname' => 'CV','name' => 'Cape Verde','phonecode' => '238'),
            array('id' => '40','shortname' => 'KY','name' => 'Cayman Islands','phonecode' => '1345'),
            array('id' => '41','shortname' => 'CF','name' => 'Central African Republic','phonecode' => '236'),
            array('id' => '42','shortname' => 'TD','name' => 'Chad','phonecode' => '235'),
            array('id' => '43','shortname' => 'CL','name' => 'Chile','phonecode' => '56'),
            array('id' => '44','shortname' => 'CN','name' => 'China','phonecode' => '86'),
            array('id' => '45','shortname' => 'CX','name' => 'Christmas Island','phonecode' => '61'),
            array('id' => '46','shortname' => 'CC','name' => 'Cocos (Keeling) Islands','phonecode' => '672'),
            array('id' => '47','shortname' => 'CO','name' => 'Colombia','phonecode' => '57'),
            array('id' => '48','shortname' => 'KM','name' => 'Comoros','phonecode' => '269'),
            array('id' => '49','shortname' => 'CG','name' => 'Republic Of The Congo','phonecode' => '242'),
            array('id' => '50','shortname' => 'CD','name' => 'Democratic Republic Of The Congo','phonecode' => '242'),
            array('id' => '51','shortname' => 'CK','name' => 'Cook Islands','phonecode' => '682'),
            array('id' => '52','shortname' => 'CR','name' => 'Costa Rica','phonecode' => '506'),
            array('id' => '53','shortname' => 'CI','name' => 'Cote D\'Ivoire (Ivory Coast)','phonecode' => '225'),
            array('id' => '54','shortname' => 'HR','name' => 'Croatia (Hrvatska)','phonecode' => '385'),
            array('id' => '55','shortname' => 'CU','name' => 'Cuba','phonecode' => '53'),
            array('id' => '56','shortname' => 'CY','name' => 'Cyprus','phonecode' => '357'),
            array('id' => '57','shortname' => 'CZ','name' => 'Czech Republic','phonecode' => '420'),
            array('id' => '58','shortname' => 'DK','name' => 'Denmark','phonecode' => '45'),
            array('id' => '59','shortname' => 'DJ','name' => 'Djibouti','phonecode' => '253'),
            array('id' => '60','shortname' => 'DM','name' => 'Dominica','phonecode' => '1767'),
            array('id' => '61','shortname' => 'DO','name' => 'Dominican Republic','phonecode' => '1809'),
            array('id' => '62','shortname' => 'TP','name' => 'East Timor','phonecode' => '670'),
            array('id' => '63','shortname' => 'EC','name' => 'Ecuador','phonecode' => '593'),
            array('id' => '64','shortname' => 'EG','name' => 'Egypt','phonecode' => '20'),
            array('id' => '65','shortname' => 'SV','name' => 'El Salvador','phonecode' => '503'),
            array('id' => '66','shortname' => 'GQ','name' => 'Equatorial Guinea','phonecode' => '240'),
            array('id' => '67','shortname' => 'ER','name' => 'Eritrea','phonecode' => '291'),
            array('id' => '68','shortname' => 'EE','name' => 'Estonia','phonecode' => '372'),
            array('id' => '69','shortname' => 'ET','name' => 'Ethiopia','phonecode' => '251'),
            array('id' => '70','shortname' => 'XA','name' => 'External Territories of Australia','phonecode' => '61'),
            array('id' => '71','shortname' => 'FK','name' => 'Falkland Islands','phonecode' => '500'),
            array('id' => '72','shortname' => 'FO','name' => 'Faroe Islands','phonecode' => '298'),
            array('id' => '73','shortname' => 'FJ','name' => 'Fiji Islands','phonecode' => '679'),
            array('id' => '74','shortname' => 'FI','name' => 'Finland','phonecode' => '358'),
            array('id' => '75','shortname' => 'FR','name' => 'France','phonecode' => '33'),
            array('id' => '76','shortname' => 'GF','name' => 'French Guiana','phonecode' => '594'),
            array('id' => '77','shortname' => 'PF','name' => 'French Polynesia','phonecode' => '689'),
            array('id' => '78','shortname' => 'TF','name' => 'French Southern Territories','phonecode' => '0'),
            array('id' => '79','shortname' => 'GA','name' => 'Gabon','phonecode' => '241'),
            array('id' => '80','shortname' => 'GM','name' => 'Gambia The','phonecode' => '220'),
            array('id' => '81','shortname' => 'GE','name' => 'Georgia','phonecode' => '995'),
            array('id' => '82','shortname' => 'DE','name' => 'Germany','phonecode' => '49'),
            array('id' => '83','shortname' => 'GH','name' => 'Ghana','phonecode' => '233'),
            array('id' => '84','shortname' => 'GI','name' => 'Gibraltar','phonecode' => '350'),
            array('id' => '85','shortname' => 'GR','name' => 'Greece','phonecode' => '30'),
            array('id' => '86','shortname' => 'GL','name' => 'Greenland','phonecode' => '299'),
            array('id' => '87','shortname' => 'GD','name' => 'Grenada','phonecode' => '1473'),
            array('id' => '88','shortname' => 'GP','name' => 'Guadeloupe','phonecode' => '590'),
            array('id' => '89','shortname' => 'GU','name' => 'Guam','phonecode' => '1671'),
            array('id' => '90','shortname' => 'GT','name' => 'Guatemala','phonecode' => '502'),
            array('id' => '91','shortname' => 'XU','name' => 'Guernsey and Alderney','phonecode' => '44'),
            array('id' => '92','shortname' => 'GN','name' => 'Guinea','phonecode' => '224'),
            array('id' => '93','shortname' => 'GW','name' => 'Guinea-Bissau','phonecode' => '245'),
            array('id' => '94','shortname' => 'GY','name' => 'Guyana','phonecode' => '592'),
            array('id' => '95','shortname' => 'HT','name' => 'Haiti','phonecode' => '509'),
            array('id' => '96','shortname' => 'HM','name' => 'Heard and McDonald Islands','phonecode' => '0'),
            array('id' => '97','shortname' => 'HN','name' => 'Honduras','phonecode' => '504'),
            array('id' => '98','shortname' => 'HK','name' => 'Hong Kong S.A.R.','phonecode' => '852'),
            array('id' => '99','shortname' => 'HU','name' => 'Hungary','phonecode' => '36'),
            array('id' => '100','shortname' => 'IS','name' => 'Iceland','phonecode' => '354'),
            array('id' => '101','shortname' => 'IN','name' => 'India','phonecode' => '91'),
            array('id' => '102','shortname' => 'ID','name' => 'Indonesia','phonecode' => '62'),
            array('id' => '103','shortname' => 'IR','name' => 'Iran','phonecode' => '98'),
            array('id' => '104','shortname' => 'IQ','name' => 'Iraq','phonecode' => '964'),
            array('id' => '105','shortname' => 'IE','name' => 'Ireland','phonecode' => '353'),
            array('id' => '106','shortname' => 'IL','name' => 'Israel','phonecode' => '972'),
            array('id' => '107','shortname' => 'IT','name' => 'Italy','phonecode' => '39'),
            array('id' => '108','shortname' => 'JM','name' => 'Jamaica','phonecode' => '1876'),
            array('id' => '109','shortname' => 'JP','name' => 'Japan','phonecode' => '81'),
            array('id' => '110','shortname' => 'XJ','name' => 'Jersey','phonecode' => '44'),
            array('id' => '111','shortname' => 'JO','name' => 'Jordan','phonecode' => '962'),
            array('id' => '112','shortname' => 'KZ','name' => 'Kazakhstan','phonecode' => '7'),
            array('id' => '113','shortname' => 'KE','name' => 'Kenya','phonecode' => '254'),
            array('id' => '114','shortname' => 'KI','name' => 'Kiribati','phonecode' => '686'),
            array('id' => '115','shortname' => 'KP','name' => 'Korea North','phonecode' => '850'),
            array('id' => '116','shortname' => 'KR','name' => 'Korea South','phonecode' => '82'),
            array('id' => '117','shortname' => 'KW','name' => 'Kuwait','phonecode' => '965'),
            array('id' => '118','shortname' => 'KG','name' => 'Kyrgyzstan','phonecode' => '996'),
            array('id' => '119','shortname' => 'LA','name' => 'Laos','phonecode' => '856'),
            array('id' => '120','shortname' => 'LV','name' => 'Latvia','phonecode' => '371'),
            array('id' => '121','shortname' => 'LB','name' => 'Lebanon','phonecode' => '961'),
            array('id' => '122','shortname' => 'LS','name' => 'Lesotho','phonecode' => '266'),
            array('id' => '123','shortname' => 'LR','name' => 'Liberia','phonecode' => '231'),
            array('id' => '124','shortname' => 'LY','name' => 'Libya','phonecode' => '218'),
            array('id' => '125','shortname' => 'LI','name' => 'Liechtenstein','phonecode' => '423'),
            array('id' => '126','shortname' => 'LT','name' => 'Lithuania','phonecode' => '370'),
            array('id' => '127','shortname' => 'LU','name' => 'Luxembourg','phonecode' => '352'),
            array('id' => '128','shortname' => 'MO','name' => 'Macau S.A.R.','phonecode' => '853'),
            array('id' => '129','shortname' => 'MK','name' => 'Macedonia','phonecode' => '389'),
            array('id' => '130','shortname' => 'MG','name' => 'Madagascar','phonecode' => '261'),
            array('id' => '131','shortname' => 'MW','name' => 'Malawi','phonecode' => '265'),
            array('id' => '132','shortname' => 'MY','name' => 'Malaysia','phonecode' => '60'),
            array('id' => '133','shortname' => 'MV','name' => 'Maldives','phonecode' => '960'),
            array('id' => '134','shortname' => 'ML','name' => 'Mali','phonecode' => '223'),
            array('id' => '135','shortname' => 'MT','name' => 'Malta','phonecode' => '356'),
            array('id' => '136','shortname' => 'XM','name' => 'Man (Isle of)','phonecode' => '44'),
            array('id' => '137','shortname' => 'MH','name' => 'Marshall Islands','phonecode' => '692'),
            array('id' => '138','shortname' => 'MQ','name' => 'Martinique','phonecode' => '596'),
            array('id' => '139','shortname' => 'MR','name' => 'Mauritania','phonecode' => '222'),
            array('id' => '140','shortname' => 'MU','name' => 'Mauritius','phonecode' => '230'),
            array('id' => '141','shortname' => 'YT','name' => 'Mayotte','phonecode' => '269'),
            array('id' => '142','shortname' => 'MX','name' => 'Mexico','phonecode' => '52'),
            array('id' => '143','shortname' => 'FM','name' => 'Micronesia','phonecode' => '691'),
            array('id' => '144','shortname' => 'MD','name' => 'Moldova','phonecode' => '373'),
            array('id' => '145','shortname' => 'MC','name' => 'Monaco','phonecode' => '377'),
            array('id' => '146','shortname' => 'MN','name' => 'Mongolia','phonecode' => '976'),
            array('id' => '147','shortname' => 'MS','name' => 'Montserrat','phonecode' => '1664'),
            array('id' => '148','shortname' => 'MA','name' => 'Morocco','phonecode' => '212'),
            array('id' => '149','shortname' => 'MZ','name' => 'Mozambique','phonecode' => '258'),
            array('id' => '150','shortname' => 'MM','name' => 'Myanmar','phonecode' => '95'),
            array('id' => '151','shortname' => 'NA','name' => 'Namibia','phonecode' => '264'),
            array('id' => '152','shortname' => 'NR','name' => 'Nauru','phonecode' => '674'),
            array('id' => '153','shortname' => 'NP','name' => 'Nepal','phonecode' => '977'),
            array('id' => '154','shortname' => 'AN','name' => 'Netherlands Antilles','phonecode' => '599'),
            array('id' => '155','shortname' => 'NL','name' => 'Netherlands The','phonecode' => '31'),
            array('id' => '156','shortname' => 'NC','name' => 'New Caledonia','phonecode' => '687'),
            array('id' => '157','shortname' => 'NZ','name' => 'New Zealand','phonecode' => '64'),
            array('id' => '158','shortname' => 'NI','name' => 'Nicaragua','phonecode' => '505'),
            array('id' => '159','shortname' => 'NE','name' => 'Niger','phonecode' => '227'),
            array('id' => '160','shortname' => 'NG','name' => 'Nigeria','phonecode' => '234'),
            array('id' => '161','shortname' => 'NU','name' => 'Niue','phonecode' => '683'),
            array('id' => '162','shortname' => 'NF','name' => 'Norfolk Island','phonecode' => '672'),
            array('id' => '163','shortname' => 'MP','name' => 'Northern Mariana Islands','phonecode' => '1670'),
            array('id' => '164','shortname' => 'NO','name' => 'Norway','phonecode' => '47'),
            array('id' => '165','shortname' => 'OM','name' => 'Oman','phonecode' => '968'),
            array('id' => '166','shortname' => 'PK','name' => 'Pakistan','phonecode' => '92'),
            array('id' => '167','shortname' => 'PW','name' => 'Palau','phonecode' => '680'),
            array('id' => '168','shortname' => 'PS','name' => 'Palestinian Territory Occupied','phonecode' => '970'),
            array('id' => '169','shortname' => 'PA','name' => 'Panama','phonecode' => '507'),
            array('id' => '170','shortname' => 'PG','name' => 'Papua new Guinea','phonecode' => '675'),
            array('id' => '171','shortname' => 'PY','name' => 'Paraguay','phonecode' => '595'),
            array('id' => '172','shortname' => 'PE','name' => 'Peru','phonecode' => '51'),
            array('id' => '173','shortname' => 'PH','name' => 'Philippines','phonecode' => '63'),
            array('id' => '174','shortname' => 'PN','name' => 'Pitcairn Island','phonecode' => '0'),
            array('id' => '175','shortname' => 'PL','name' => 'Poland','phonecode' => '48'),
            array('id' => '176','shortname' => 'PT','name' => 'Portugal','phonecode' => '351'),
            array('id' => '177','shortname' => 'PR','name' => 'Puerto Rico','phonecode' => '1787'),
            array('id' => '178','shortname' => 'QA','name' => 'Qatar','phonecode' => '974'),
            array('id' => '179','shortname' => 'RE','name' => 'Reunion','phonecode' => '262'),
            array('id' => '180','shortname' => 'RO','name' => 'Romania','phonecode' => '40'),
            array('id' => '181','shortname' => 'RU','name' => 'Russia','phonecode' => '70'),
            array('id' => '182','shortname' => 'RW','name' => 'Rwanda','phonecode' => '250'),
            array('id' => '183','shortname' => 'SH','name' => 'Saint Helena','phonecode' => '290'),
            array('id' => '184','shortname' => 'KN','name' => 'Saint Kitts And Nevis','phonecode' => '1869'),
            array('id' => '185','shortname' => 'LC','name' => 'Saint Lucia','phonecode' => '1758'),
            array('id' => '186','shortname' => 'PM','name' => 'Saint Pierre and Miquelon','phonecode' => '508'),
            array('id' => '187','shortname' => 'VC','name' => 'Saint Vincent And The Grenadines','phonecode' => '1784'),
            array('id' => '188','shortname' => 'WS','name' => 'Samoa','phonecode' => '684'),
            array('id' => '189','shortname' => 'SM','name' => 'San Marino','phonecode' => '378'),
            array('id' => '190','shortname' => 'ST','name' => 'Sao Tome and Principe','phonecode' => '239'),
            array('id' => '191','shortname' => 'SA','name' => 'Saudi Arabia','phonecode' => '966'),
            array('id' => '192','shortname' => 'SN','name' => 'Senegal','phonecode' => '221'),
            array('id' => '193','shortname' => 'RS','name' => 'Serbia','phonecode' => '381'),
            array('id' => '194','shortname' => 'SC','name' => 'Seychelles','phonecode' => '248'),
            array('id' => '195','shortname' => 'SL','name' => 'Sierra Leone','phonecode' => '232'),
            array('id' => '196','shortname' => 'SG','name' => 'Singapore','phonecode' => '65'),
            array('id' => '197','shortname' => 'SK','name' => 'Slovakia','phonecode' => '421'),
            array('id' => '198','shortname' => 'SI','name' => 'Slovenia','phonecode' => '386'),
            array('id' => '199','shortname' => 'XG','name' => 'Smaller Territories of the UK','phonecode' => '44'),
            array('id' => '200','shortname' => 'SB','name' => 'Solomon Islands','phonecode' => '677'),
            array('id' => '201','shortname' => 'SO','name' => 'Somalia','phonecode' => '252'),
            array('id' => '202','shortname' => 'ZA','name' => 'South Africa','phonecode' => '27'),
            array('id' => '203','shortname' => 'GS','name' => 'South Georgia','phonecode' => '0'),
            array('id' => '204','shortname' => 'SS','name' => 'South Sudan','phonecode' => '211'),
            array('id' => '205','shortname' => 'ES','name' => 'Spain','phonecode' => '34'),
            array('id' => '206','shortname' => 'LK','name' => 'Sri Lanka','phonecode' => '94'),
            array('id' => '207','shortname' => 'SD','name' => 'Sudan','phonecode' => '249'),
            array('id' => '208','shortname' => 'SR','name' => 'Suriname','phonecode' => '597'),
            array('id' => '209','shortname' => 'SJ','name' => 'Svalbard And Jan Mayen Islands','phonecode' => '47'),
            array('id' => '210','shortname' => 'SZ','name' => 'Swaziland','phonecode' => '268'),
            array('id' => '211','shortname' => 'SE','name' => 'Sweden','phonecode' => '46'),
            array('id' => '212','shortname' => 'CH','name' => 'Switzerland','phonecode' => '41'),
            array('id' => '213','shortname' => 'SY','name' => 'Syria','phonecode' => '963'),
            array('id' => '214','shortname' => 'TW','name' => 'Taiwan','phonecode' => '886'),
            array('id' => '215','shortname' => 'TJ','name' => 'Tajikistan','phonecode' => '992'),
            array('id' => '216','shortname' => 'TZ','name' => 'Tanzania','phonecode' => '255'),
            array('id' => '217','shortname' => 'TH','name' => 'Thailand','phonecode' => '66'),
            array('id' => '218','shortname' => 'TG','name' => 'Togo','phonecode' => '228'),
            array('id' => '219','shortname' => 'TK','name' => 'Tokelau','phonecode' => '690'),
            array('id' => '220','shortname' => 'TO','name' => 'Tonga','phonecode' => '676'),
            array('id' => '221','shortname' => 'TT','name' => 'Trinidad And Tobago','phonecode' => '1868'),
            array('id' => '222','shortname' => 'TN','name' => 'Tunisia','phonecode' => '216'),
            array('id' => '223','shortname' => 'TR','name' => 'Turkey','phonecode' => '90'),
            array('id' => '224','shortname' => 'TM','name' => 'Turkmenistan','phonecode' => '7370'),
            array('id' => '225','shortname' => 'TC','name' => 'Turks And Caicos Islands','phonecode' => '1649'),
            array('id' => '226','shortname' => 'TV','name' => 'Tuvalu','phonecode' => '688'),
            array('id' => '227','shortname' => 'UG','name' => 'Uganda','phonecode' => '256'),
            array('id' => '228','shortname' => 'UA','name' => 'Ukraine','phonecode' => '380'),
            array('id' => '229','shortname' => 'AE','name' => 'United Arab Emirates','phonecode' => '971'),
            array('id' => '230','shortname' => 'GB','name' => 'United Kingdom','phonecode' => '44'),
            array('id' => '231','shortname' => 'US','name' => 'United States','phonecode' => '1'),
            array('id' => '232','shortname' => 'UM','name' => 'United States Minor Outlying Islands','phonecode' => '1'),
            array('id' => '233','shortname' => 'UY','name' => 'Uruguay','phonecode' => '598'),
            array('id' => '234','shortname' => 'UZ','name' => 'Uzbekistan','phonecode' => '998'),
            array('id' => '235','shortname' => 'VU','name' => 'Vanuatu','phonecode' => '678'),
            array('id' => '236','shortname' => 'VA','name' => 'Vatican City State (Holy See)','phonecode' => '39'),
            array('id' => '237','shortname' => 'VE','name' => 'Venezuela','phonecode' => '58'),
            array('id' => '238','shortname' => 'VN','name' => 'Vietnam','phonecode' => '84'),
            array('id' => '239','shortname' => 'VG','name' => 'Virgin Islands (British)','phonecode' => '1284'),
            array('id' => '240','shortname' => 'VI','name' => 'Virgin Islands (US)','phonecode' => '1340'),
            array('id' => '241','shortname' => 'WF','name' => 'Wallis And Futuna Islands','phonecode' => '681'),
            array('id' => '242','shortname' => 'EH','name' => 'Western Sahara','phonecode' => '212'),
            array('id' => '243','shortname' => 'YE','name' => 'Yemen','phonecode' => '967'),
            array('id' => '244','shortname' => 'YU','name' => 'Yugoslavia','phonecode' => '38'),
            array('id' => '245','shortname' => 'ZM','name' => 'Zambia','phonecode' => '260'),
            array('id' => '246','shortname' => 'ZW','name' => 'Zimbabwe','phonecode' => '263')
          );
          Country::insert($countries);
    }
}
