<?php

namespace Database\Seeders;

use App\Constants\AppConstants;
use App\Constants\CurrencyConstants;
use App\Constants\PropertyConstants;
use App\Models\Country;
use App\Models\Property;
use App\Models\PropertyCategory;
use App\Models\State;
use App\Models\User;
use App\Services\Finance\CurrencyService;
use App\Services\Property\PropertyService;
use Illuminate\Database\Seeder;

class PropertyTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $user = User::first();
        $category = PropertyCategory::inRandomOrder()->first();
        $currency = CurrencyService::getByType(CurrencyConstants::POUND_CURRENCY);
        $country = Country::find(AppConstants::NIGERIA_ID);
        $states_id = State::where("country_id", $country->id)
            ->pluck('id')->toArray();

        $properties = [
            [
                'name' => "Test property " . rand(1, 20),
                'uuid' => uniqid(),
                'description' => "This property is a test property ",
                'country_id' => $country->id,
                'state_id' => array_rand($states_id),
                'price' => rand(100, 10000),
                'sqft' => "100",
                'bedrooms' => "2",
                'bathrooms' => "5",
                'landmark' => "Active",
                'address' => "6624 Fannin St #1700 Ikeja Lagos Nigeria",
                'avg_ratings' => 10.2,
                'total_reviews' => 10,
                'total_clicks' => 20,
                'total_sold' => 5,
                'total_slots' => 20,
                'maihomm_fee' => rand(100, 300),
                'first_year_projection' => rand(100, 300),
                'fifth_year_projection' => rand(100, 300),
                'tenth_year_projection' => rand(100, 300),
                'legal_and_closing_cost' => rand(100, 300),
                'property_acq_cost' => rand(100, 300),
                'service_charge' => rand(100, 300),
                'management_fees' => rand(100, 300),
                'projected_gross_rent' => rand(100, 300),
                'closing_date' => now(),
            ],

            [
                'name' => "Test property " . rand(1, 20),
                'uuid' => slugify("Test property " . rand(1, 30) . rand(1, 20)),
                'description' => "This property is a test property ",
                'country_id' => $country->id,
                'state_id' => array_rand($states_id),
                'price' => rand(100, 10000),
                'sqft' => "100",
                'bedrooms' => "2",
                'bathrooms' => "5",
                'landmark' => "Active",
                'address' => "6624 Fannin St #1700 Ikeja Lagos Nigeria",
                'avg_ratings' => 10.2,
                'total_reviews' => 10,
                'total_clicks' => 20,
                'total_sold' => 5,
                'total_slots' => 20,
                'maihomm_fee' => rand(100, 300),
                'first_year_projection' => rand(100, 300),
                'fifth_year_projection' => rand(100, 300),
                'tenth_year_projection' => rand(100, 300),
                'legal_and_closing_cost' => rand(100, 300),
                'property_acq_cost' => rand(100, 300),
                'service_charge' => rand(100, 300),
                'management_fees' => rand(100, 300),
                'projected_gross_rent' => rand(100, 300),
                'closing_date' => now(),
            ],

            [
                'name' => "Test property " . rand(1, 20),
                'uuid' => slugify("Test property " . rand(1, 30) . rand(1, 20)),
                'description' => "This property is a test property ",
                'country_id' => $country->id,
                'state_id' => array_rand($states_id),
                'price' => rand(100, 10000),
                'sqft' => "100",
                'bedrooms' => "2",
                'bathrooms' => "5",
                'landmark' => "Active",
                'address' => "6624 Fannin St #1700 Ikeja Lagos Nigeria",
                'avg_ratings' => 10.2,
                'total_reviews' => 10,
                'total_clicks' => 20,
                'total_sold' => 5,
                'total_slots' => 20,
                'maihomm_fee' => rand(100, 300),
                'first_year_projection' => rand(100, 300),
                'fifth_year_projection' => rand(100, 300),
                'tenth_year_projection' => rand(100, 300),
                'legal_and_closing_cost' => rand(100, 300),
                'property_acq_cost' => rand(100, 300),
                'service_charge' => rand(100, 300),
                'management_fees' => rand(100, 300),
                'projected_gross_rent' => rand(100, 300),
                'closing_date' => now(),
            ],

            [
                'name' => "Test property " . rand(1, 20),
                'uuid' => slugify("Test property " . rand(1, 30) . rand(1, 20)),
                'description' => "This property is a test property ",
                'country_id' => $country->id,
                'state_id' => array_rand($states_id),
                'price' => rand(100, 10000),
                'sqft' => "100",
                'bedrooms' => "2",
                'bathrooms' => "5",
                'landmark' => "Active",
                'address' => "6624 Fannin St #1700 Ikeja Lagos Nigeria",
                'avg_ratings' => 10.2,
                'total_reviews' => 10,
                'total_clicks' => 20,
                'total_sold' => 5,
                'total_slots' => 20,
                'maihomm_fee' => rand(100, 300),
                'first_year_projection' => rand(100, 300),
                'fifth_year_projection' => rand(100, 300),
                'tenth_year_projection' => rand(100, 300),
                'legal_and_closing_cost' => rand(100, 300),
                'property_acq_cost' => rand(100, 300),
                'service_charge' => rand(100, 300),
                'management_fees' => rand(100, 300),
                'projected_gross_rent' => rand(100, 300),
                'closing_date' => now(),
            ],

            [
                'name' => "Test property " . rand(1, 20),
                'uuid' => slugify("Test property " . rand(1, 30) . rand(1, 20)),
                'description' => "This property is a test property ",
                'country_id' => $country->id,
                'state_id' => array_rand($states_id),
                'price' => rand(100, 10000),
                'sqft' => "100",
                'bedrooms' => "2",
                'bathrooms' => "5",
                'landmark' => "Active",
                'address' => "6624 Fannin St #1700 Ikeja Lagos Nigeria",
                'avg_ratings' => 10.2,
                'total_reviews' => 10,
                'total_clicks' => 20,
                'total_sold' => 5,
                'total_slots' => 20,
                'maihomm_fee' => rand(100, 300),
                'first_year_projection' => rand(100, 300),
                'fifth_year_projection' => rand(100, 300),
                'tenth_year_projection' => rand(100, 300),
                'legal_and_closing_cost' => rand(100, 300),
                'property_acq_cost' => rand(100, 300),
                'service_charge' => rand(100, 300),
                'management_fees' => rand(100, 300),
                'projected_gross_rent' => rand(100, 300),
                'closing_date' => now(),
            ],

            [
                'name' => "Test property " . rand(1, 20),
                'uuid' => slugify("Test property " . rand(1, 30) . rand(1, 20)),
                'description' => "This property is a test property ",
                'country_id' => $country->id,
                'state_id' => array_rand($states_id),
                'price' => rand(100, 10000),
                'sqft' => "100",
                'bedrooms' => "2",
                'bathrooms' => "5",
                'landmark' => "Active",
                'address' => "6624 Fannin St #1700 Ikeja Lagos Nigeria",
                'avg_ratings' => 10.2,
                'total_reviews' => 10,
                'total_clicks' => 20,
                'total_sold' => 5,
                'total_slots' => 20,
                'maihomm_fee' => rand(100, 300),
                'first_year_projection' => rand(100, 300),
                'fifth_year_projection' => rand(100, 300),
                'tenth_year_projection' => rand(100, 300),
                'legal_and_closing_cost' => rand(100, 300),
                'property_acq_cost' => rand(100, 300),
                'service_charge' => rand(100, 300),
                'management_fees' => rand(100, 300),
                'projected_gross_rent' => rand(100, 300),
                'closing_date' => now(),
            ],

            [
                'name' => "Test property " . rand(1, 20),
                'uuid' => slugify("Test property " . rand(1, 30) . rand(1, 20)),
                'description' => "This property is a test property ",
                'country_id' => $country->id,
                'state_id' => array_rand($states_id),
                'price' => rand(100, 10000),
                'sqft' => "100",
                'bedrooms' => "2",
                'bathrooms' => "5",
                'landmark' => "Active",
                'address' => "6624 Fannin St #1700 Ikeja Lagos Nigeria",
                'avg_ratings' => 10.2,
                'total_reviews' => 10,
                'total_clicks' => 20,
                'total_sold' => 5,
                'total_slots' => 20,
                'maihomm_fee' => rand(100, 300),
                'first_year_projection' => rand(100, 300),
                'fifth_year_projection' => rand(100, 300),
                'tenth_year_projection' => rand(100, 300),
                'legal_and_closing_cost' => rand(100, 300),
                'property_acq_cost' => rand(100, 300),
                'service_charge' => rand(100, 300),
                'management_fees' => rand(100, 300),
                'projected_gross_rent' => rand(100, 300),
                'closing_date' => now(),
            ],

            [
                'name' => "Test property " . rand(1, 20),
                'uuid' => slugify("Test property " . rand(1, 30) . rand(1, 20)),
                'description' => "This property is a test property ",
                'country_id' => $country->id,
                'state_id' => array_rand($states_id),
                'price' => rand(100, 10000),
                'sqft' => "100",
                'bedrooms' => "2",
                'bathrooms' => "5",
                'landmark' => "Active",
                'address' => "6624 Fannin St #1700 Ikeja Lagos Nigeria",
                'avg_ratings' => 10.2,
                'total_reviews' => 10,
                'total_clicks' => 20,
                'total_sold' => 5,
                'total_slots' => 20,
                'maihomm_fee' => rand(100, 300),
                'first_year_projection' => rand(100, 300),
                'fifth_year_projection' => rand(100, 300),
                'tenth_year_projection' => rand(100, 300),
                'legal_and_closing_cost' => rand(100, 300),
                'property_acq_cost' => rand(100, 300),
                'service_charge' => rand(100, 300),
                'management_fees' => rand(100, 300),
                'projected_gross_rent' => rand(100, 300),
                'closing_date' => now(),
            ],

            [
                'name' => "Test property " . rand(1, 20),
                'uuid' => slugify("Test property " . rand(1, 30) . rand(1, 20)),
                'description' => "This property is a test property ",
                'country_id' => $country->id,
                'state_id' => array_rand($states_id),
                'price' => rand(100, 10000),
                'sqft' => "100",
                'bedrooms' => "2",
                'bathrooms' => "5",
                'landmark' => "Active",
                'address' => "6624 Fannin St #1700 Ikeja Lagos Nigeria",
                'avg_ratings' => 10.2,
                'total_reviews' => 10,
                'total_clicks' => 20,
                'total_sold' => 5,
                'total_slots' => 20,
                'maihomm_fee' => rand(100, 300),
                'first_year_projection' => rand(100, 300),
                'fifth_year_projection' => rand(100, 300),
                'tenth_year_projection' => rand(100, 300),
                'legal_and_closing_cost' => rand(100, 300),
                'property_acq_cost' => rand(100, 300),
                'service_charge' => rand(100, 300),
                'management_fees' => rand(100, 300),
                'projected_gross_rent' => rand(100, 300),
                'closing_date' => now(),
            ],

            [
                'name' => "Test property " . rand(1, 20),
                'uuid' => slugify("Test property " . rand(1, 30) . rand(1, 20)),
                'description' => "This property is a test property ",
                'country_id' => $country->id,
                'state_id' => array_rand($states_id),
                'price' => rand(100, 10000),
                'sqft' => "100",
                'bedrooms' => "2",
                'bathrooms' => "5",
                'landmark' => "Active",
                'address' => "6624 Fannin St #1700 Ikeja Lagos Nigeria",
                'avg_ratings' => 10.2,
                'total_reviews' => 10,
                'total_clicks' => 20,
                'total_sold' => 5,
                'total_slots' => 20,
                'maihomm_fee' => rand(100, 300),
                'first_year_projection' => rand(100, 300),
                'fifth_year_projection' => rand(100, 300),
                'tenth_year_projection' => rand(100, 300),
                'legal_and_closing_cost' => rand(100, 300),
                'property_acq_cost' => rand(100, 300),
                'service_charge' => rand(100, 300),
                'management_fees' => rand(100, 300),
                'projected_gross_rent' => rand(100, 300),
                'closing_date' => now(),
            ],

            [
                'name' => "Test property " . rand(1, 20),
                'uuid' => slugify("Test property " . rand(1, 30) . rand(1, 20)),
                'description' => "This property is a test property ",
                'country_id' => $country->id,
                'state_id' => array_rand($states_id),
                'price' => rand(100, 10000),
                'sqft' => "100",
                'bedrooms' => "2",
                'bathrooms' => "5",
                'landmark' => "Active",
                'address' => "6624 Fannin St #1700 Ikeja Lagos Nigeria",
                'avg_ratings' => 10.2,
                'total_reviews' => 10,
                'total_clicks' => 20,
                'total_sold' => 5,
                'total_slots' => 20,
                'maihomm_fee' => rand(100, 300),
                'first_year_projection' => rand(100, 300),
                'fifth_year_projection' => rand(100, 300),
                'tenth_year_projection' => rand(100, 300),
                'legal_and_closing_cost' => rand(100, 300),
                'property_acq_cost' => rand(100, 300),
                'service_charge' => rand(100, 300),
                'management_fees' => rand(100, 300),
                'projected_gross_rent' => rand(100, 300),
                'closing_date' => now(),
            ],

            [
                'name' => "Test property " . rand(1, 20),
                'uuid' => slugify("Test property " . rand(1, 30) . rand(1, 20)),
                'description' => "This property is a test property ",
                'country_id' => $country->id,
                'state_id' => array_rand($states_id),
                'price' => rand(100, 10000),
                'sqft' => "100",
                'bedrooms' => "2",
                'bathrooms' => "5",
                'landmark' => "Active",
                'address' => "6624 Fannin St #1700 Ikeja Lagos Nigeria",
                'avg_ratings' => 10.2,
                'total_reviews' => 10,
                'total_clicks' => 20,
                'total_sold' => 5,
                'total_slots' => 20,
                'maihomm_fee' => rand(100, 300),
                'first_year_projection' => rand(100, 300),
                'fifth_year_projection' => rand(100, 300),
                'tenth_year_projection' => rand(100, 300),
                'legal_and_closing_cost' => rand(100, 300),
                'property_acq_cost' => rand(100, 300),
                'service_charge' => rand(100, 300),
                'management_fees' => rand(100, 300),
                'projected_gross_rent' => rand(100, 300),
                'closing_date' => now(),
            ],

            [
                'name' => "Test property " . rand(1, 20),
                'uuid' => slugify("Test property " . rand(1, 30) . rand(1, 20)),
                'description' => "This property is a test property ",
                'country_id' => $country->id,
                'state_id' => array_rand($states_id),
                'price' => rand(100, 10000),
                'sqft' => "100",
                'bedrooms' => "2",
                'bathrooms' => "5",
                'landmark' => "Active",
                'address' => "6624 Fannin St #1700 Ikeja Lagos Nigeria",
                'avg_ratings' => 10.2,
                'total_reviews' => 10,
                'total_clicks' => 20,
                'total_sold' => 5,
                'total_slots' => 20,
                'maihomm_fee' => rand(100, 300),
                'first_year_projection' => rand(100, 300),
                'fifth_year_projection' => rand(100, 300),
                'tenth_year_projection' => rand(100, 300),
                'legal_and_closing_cost' => rand(100, 300),
                'property_acq_cost' => rand(100, 300),
                'service_charge' => rand(100, 300),
                'management_fees' => rand(100, 300),
                'projected_gross_rent' => rand(100, 300),
                'closing_date' => now(),
            ],

            [
                'name' => "Test property " . rand(1, 20),
                'uuid' => slugify("Test property " . rand(1, 30) . rand(1, 20)),
                'description' => "This property is a test property ",
                'country_id' => $country->id,
                'state_id' => array_rand($states_id),
                'price' => rand(100, 10000),
                'sqft' => "100",
                'bedrooms' => "2",
                'bathrooms' => "5",
                'landmark' => "Active",
                'address' => "6624 Fannin St #1700 Ikeja Lagos Nigeria",
                'avg_ratings' => 10.2,
                'total_reviews' => 10,
                'total_clicks' => 20,
                'total_sold' => 5,
                'total_slots' => 20,
                'maihomm_fee' => rand(100, 300),
                'first_year_projection' => rand(100, 300),
                'fifth_year_projection' => rand(100, 300),
                'tenth_year_projection' => rand(100, 300),
                'legal_and_closing_cost' => rand(100, 300),
                'property_acq_cost' => rand(100, 300),
                'service_charge' => rand(100, 300),
                'management_fees' => rand(100, 300),
                'projected_gross_rent' => rand(100, 300),
                'closing_date' => now(),
            ],
        ];

        foreach ($properties as $key => $property) {
            $property = array_merge($property , [
                "status" => PropertyConstants::STATUS_AVAILABLE,
                'category_id' => $category->id,
                'currency_id' => $currency->id,
                'created_by' => $user->id,
                'per_slot' => number_format($property['price'] / $property['total_slots'], 2)
            ]);
            PropertyService::create($property);
        }
    }
}
